[versions]
kotlinx-coroutines = "1.9.0"
slf4j = "2.0.16"
urilib = "1.0.12"
netty = "4.1.114.Final"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

urilib = { module = "com.oxyggen.net:urilib", version.ref = "urilib" }
